---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-App-Cmd
no_index:
  directory:
    - t
    - inc
requires:
  App::Cmd: 0.3
  Getopt::Long::Descriptive: 0
  Moose: 0.86
  MooseX::Getopt: 0.18
  Test::use::ok: 0
version: 0.07
